spring.application.name=wemouv

# SQL (Production - injecté par le serveur)
#spring.datasource.url=${PROD_DB_URL}
#.datasource.username=${PROD_DB_USER}
#spring.datasource.password=${PROD_DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=validate

# Logs moins verbeux pour la performance
logging.level.root=INFO

# MAIL (injecté par le serveur)
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}

# JWT (injecté par le serveur)
jwt.secret=${JWT_SECRET}

# Configuration de la base de données H2 (En mémoire)
spring.datasource.url=jdbc:h2:mem:wemouvdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Création automatique des tables
spring.jpa.hibernate.ddl-auto=update

# Optionnel : pour voir la base de données sur /h2-console
spring.h2.console.enabled=true